# Generated by Django 4.2.5 on 2023-09-17 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_menu_menu_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allergy",
            name="allergy_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="ingredient_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="menu",
            name="menu_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="region",
            name="region_type",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="vegetarian",
            name="vegetarian_name",
            field=models.CharField(max_length=50),
        ),
    ]
