# Generated by Django 4.2.5 on 2023-09-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_remove_allergy_ingredient_allergy_allergy_ingredient"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_name",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
