# Generated by Django 4.2.5 on 2023-09-21 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_user_user_name"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Region",
            new_name="Religion",
        ),
        migrations.RenameField(
            model_name="religion",
            old_name="region_ingredient",
            new_name="religion_ingredient",
        ),
        migrations.RenameField(
            model_name="religion",
            old_name="region_type",
            new_name="religion_type",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="region",
            new_name="religion",
        ),
    ]
