# Generated by Django 4.2.5 on 2023-09-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_alter_user_religion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_allergy",
            field=models.ManyToManyField(blank=True, to="api.allergy"),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_vegetarian",
            field=models.ManyToManyField(blank=True, to="api.vegetarian"),
        ),
    ]
