# Generated by Django 4.2.5 on 2023-09-25 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_alter_user_user_allergy_alter_user_user_vegetarian"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="user_vegetarian",
        ),
        migrations.AddField(
            model_name="user",
            name="user_vegetarian",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.vegetarian",
            ),
        ),
    ]
