# Generated by Django 4.2.5 on 2023-09-25 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_remove_user_user_vegetarian_user_user_vegetarian"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("menucategory_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="OptionCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("optioncategory_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="menu",
            name="menucategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.menucategory",
            ),
        ),
        migrations.AddField(
            model_name="option",
            name="optioncategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.optioncategory",
            ),
        ),
    ]
