# Generated by Django 4.2.5 on 2023-09-17 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_allergy_allergy_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("option_name", models.CharField(max_length=100)),
                ("option_price", models.PositiveIntegerField()),
                ("option_pic", models.CharField(max_length=500)),
                ("option_introduction", models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name="menu",
            name="menu_introduction",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="menu",
            name="menu_option",
            field=models.ManyToManyField(to="api.option"),
        ),
    ]
