# Generated by Django 4.2.5 on 2023-09-17 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_option_menu_menu_introduction_menu_menu_option"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="menu_pic",
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="option",
            name="option_pic",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_phonenum",
            field=models.CharField(max_length=13, null=True),
        ),
    ]
