# Generated by Django 4.2.5 on 2023-09-17 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_menu_menu_pic_alter_option_option_pic_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="region",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="api.region"
            ),
        ),
    ]
