# Generated by Django 4.2.5 on 2023-10-01 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_remove_ordered_item_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordered_item',
            name='order',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='signup.order'),
        ),
    ]
