# Generated by Django 4.2.5 on 2023-10-01 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_ordered_item_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordered_item',
            name='option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='signup.option'),
        ),
    ]
