# Generated by Django 4.2.5 on 2023-10-01 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0006_alter_order_order_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordered_item',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.order'),
        ),
    ]
