# Generated by Django 4.2.5 on 2023-10-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0007_alter_ordered_item_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_pic',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
