# Generated by Django 4.2.5 on 2023-10-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0008_alter_menu_menu_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_pic',
            field=models.ImageField(blank=True, null=True, upload_to='menu'),
        ),
        migrations.AlterField(
            model_name='option',
            name='option_pic',
            field=models.ImageField(blank=True, null=True, upload_to='option'),
        ),
    ]
