# Generated by Django 4.2.5 on 2023-11-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0009_alter_menu_menu_pic_alter_option_option_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_face_info',
            field=models.TextField(null=True),
        ),
    ]
