# Generated by Django 4.2.5 on 2023-11-07 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signup", "0010_user_user_face_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_time",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
