# Generated by Django 4.2.5 on 2023-12-01 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("signup", "0013_ordered_item_menu_num"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreprocessedData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="signup.order"
                    ),
                ),
                (
                    "ordered_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="signup.ordered_item",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="signup.user"
                    ),
                ),
            ],
        ),
    ]
