# Generated by Django 4.2.5 on 2023-12-01 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("signup", "0014_preprocesseddata"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="preprocesseddata",
            name="order",
        ),
        migrations.RemoveField(
            model_name="preprocesseddata",
            name="ordered_item",
        ),
    ]
