# Generated by Django 4.2.5 on 2023-12-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signup", "0015_remove_preprocesseddata_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="preprocesseddata",
            name="excluded_ingredients",
            field=models.TextField(null=True),
        ),
    ]
