# Generated by Django 4.2.5 on 2023-12-12 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0016_preprocesseddata_excluded_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_option',
            field=models.ManyToManyField(null=True, to='signup.option'),
        ),
    ]
